services:
  graph_generator_ba:
    build:
      context: .
      dockerfile: docker/BA.Dockerfile
    volumes:
      - ./data/graphs/ba:/app/data/graphs/ba
    entrypoint: ["Rscript", "/app/generate_ba_graph.R"]
    command: ["100", "3", "5"]

  graph_generator_er:
    build:
      context: .
      dockerfile: docker/ER.Dockerfile
    volumes:
      - ./data/graphs/er:/app/data/graphs/er
    entrypoint: ["Rscript", "/app/generate_er_graph.R"]
    command: ["50", "0.1", "4"]
