services:
  graph_generator_ba:
    build:
      context: .
      dockerfile: docker/BA.Dockerfile
    volumes:
      - ./data/graphs/ba:/app/data/graphs/ba
    entrypoint: ["Rscript", "/app/generate_ba_graph.R"]
    # <num_nodes> <edges_per_step> <num_graphs>
    command: ["100", "3", "5"]

  graph_generator_er:
    build:
      context: .
      dockerfile: docker/ER.Dockerfile
    volumes:
      - ./data/graphs/er:/app/data/graphs/er
    entrypoint: ["Rscript", "/app/generate_er_graph.R"]
    # <num_nodes> <edge_probability> <num_graphs>
    command: ["50", "0.1", "4"]

  graph_generator_ws:
    build:
      context: .
      dockerfile: docker/WS.Dockerfile
    volumes:
      - ./data/graphs/ws:/app/data/graphs/ws
    entrypoint: ["Rscript", "/app/generate_ws_graph.R"]
    # <num_nodes> <neighborhood_size> <rewiring_prob> <num_graphs>
    command: ["50", "2", "0.1", "4"] 
    
